os: linux
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
    - "~/.m2/repository"
before_install:
  - bash .util/build_xatkit.sh
  - bash .util/build_chat-platform.sh

script:
  - mvn install